version: '3.8'

services:
   db:
      image: kartoza/postgis:${POSTGIS_VERSION_TAG}
      hostname: db
      container_name: db
      volumes:
        - ${PWD}/data:/var/lib/postgresql
      ports:
        - ${POSTGRES_PORT}:5432
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - POSTGRES_UID=${POSTGRES_UID}
        - POSTGRES_GID=${POSTGRES_GID}
        - ALLOW_IP_RANGE=all
        - FORCE_SSL=FALSE
      restart: on-failure
      healthcheck:
        test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
